navbarPage(title = "Trianglular Tables",
           header = tagList(
             includeCSS("www/code.css")
           ),
           tabPanel(title = "Development Triangles",
                    tags$p("When we think of tables, we typically think of rectangular data structures. And while tabular data may most often take a rectangular shape, there are times when another shape may be more appropriate. Claim payment data used by insurance companies is one such example of this."),
                    tags$p("In some types of insurance, claims can stay open for many years as claim payments continue to be made. This means that it may take many years to know the total amount paid out on all claims opened in a given year. It is common to analyze claim payments for each year in 12 months increments. For example, payments for claims occurring in the year 2015 would be considered to be \"at 12 months\" at the end of 2015, \"at 24 months\" at the end of 2016, \"at 36 months\" at the end of 2017, etc. The raw data may look like this:"),
                    fluidRow(column(width = 12,
                                    style = "text-align:center;",
                                    tags$div(DTOutput(outputId = "rawData"), style = "width:50%; margin:auto;"))),
                    br(),
                    tags$p("By pivoting this data into a wider format, we can look at how claim payments for each year develop over time (left). Then by taking ratios of each pair of adjacent columns, we can look at the percentage change in claim payments over each 12 month period (right). These ratios are called loss development factors."),
                    fluidRow(column(width = 6,
                                    DTOutput(outputId = "lossTriangle")),
                             column(width = 6,
                                    DTOutput(outputId = "devTriangle"))),
                    br(),
                    tags$p("What you probably immediately notice about the above tables is that the data naturally takes a triangular shape, leaving half the cells in the table empty. Besides not looking very great, these tables are not very helpful for actuaries and other insurance professionals who are looking at and analyzing claim payment patterns on a daily basis."),
                    tags$p(HTML("We will focus on the loss development factors (above, right) for two hypothetical states and, using the <code>DT</code> package, attempt to clean up the table as well as make it interactive to assist with analysis.")),
                    fluidRow(column(width = 12,
                                    tags$p(tags$ul(tags$li("Select State A or State B to show the corresponding loss development triangle."),
                                                   tags$li("Toggle the Heat Map switch to help visualize the size of each development factor relative to the other factors in the column."),
                                                   tags$li("Click on a development factor to show details about that factor below the table."))))
                    ),
                    br(),
                    fluidRow(column(width = 3,
                                    radioGroupButtons(inputId = "state",
                                                      label = NULL,
                                                      choices = c("State A", "State B"),
                                                      selected = "State A",
                                                      size = "normal")),
                             column(width = 6,
                                    prettySwitch(inputId = "heatMap",
                                                 label = "Heat Map",
                                                 value = FALSE,
                                                 fill = TRUE))
                    ),
                    fluidRow(column(width = 12,
                                    DTOutput(outputId = "devTriangleFormatted"))
                    ),
                    br(),
                    fluidRow(column(width = 12,
                                    tags$p("In practice, actuaries may find it useful to see a table of all the claims that make up a development factor. For simplicity, we'll just show the total claim payments at the current and previous report."),
                                    verbatimTextOutput(outputId = "factorDetail"))
                    ),
                    br(),
                    fluidRow(column(width = 12,
                                    tags$p("We can look at various averages of development factors for each column. When determing what averages to select, actuaries need to weigh stability (long-term averages) with responsiveness (short-term averages)."),
                                    DTOutput(outputId = "averages"))
                    ),
                    br(),
                    fluidRow(column(width = 12,
                                    tags$p("Using one of the sets of average development factors, we can \"complete\" the claim payments triangle by filling in the values that haven't emerged yet with their estimated values."),
                                    selectInput(inputId = "average_method",
                                                label = "Average Method",
                                                choices = c("Two Year", "Three Year", "Five Year", "All Year"),
                                                width = "10%"))
                    ),
                    fluidRow(column(width = 12,
                                    DTOutput(outputId = "lossTriangleFilled"))
                    ),
                    br(),
                    fluidRow(column(width = 12,
                                    tags$p(HTML("Please see the <a onclick=\"document.querySelector('[data-value=\\'Tutorial\\']').click(); window.scrollTo(0, 0);\">Tutorial</a> tab for a step by step guide on how to create the above tables."))))
           ),
           tabPanel(title = "Tutorial",
                    tags$p(HTML("This tutorial will focus on how the interactive loss development factors triangle and completed claim payments triangle are created. A basic understanding of the <code>DT</code> package is assumed. The data for State A on the previous tab will be used.")),
                    tags$h1("Step 1"),
                    tags$p("We start with the raw claim payment data."),
                    tags$pre(paste0(readLines("www/tutorial/step1.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step1"),
                    tags$h1("Step 2"),
                    tags$p("Pivot the data into a wide format."),
                    tags$pre(paste0(readLines("www/tutorial/step2.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step2"),
                    tags$h1("Step 3"),
                    tags$p("Divide each set of adjacent columns to calculate loss development factors."),
                    tags$pre(paste0(readLines("www/tutorial/step3.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step3"),
                    tags$h1("Step 4"),
                    tags$p(HTML("For each loss development factor, we need to determine its magnitude relative to the other factors in the same column and assign it the appropriate background color. The <code>add_highlighting</code> function will do exactly that. We also need a column to indicate whether or not to use the background colors, which can be done by adding a new column called <code>COLOR_USE</code> and setting it to <code>TRUE</code>.")),
                    tags$pre(paste0(readLines("www/tutorial/step4.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step4"),
                    tags$h1("Step 5"),
                    tags$p(HTML("Now we can put the data into a table. We can get pretty close to the final table by just using the options built into the <code>datatable</code> function. Note, however, that currently all cells in the table are selectable, including the Year column and the empty cells. We also still need to add cell borders to the cells that contains values, and we need a way to conditionally apply the background colors based on the hex colors in the hidden columns.")),
                    tags$pre(paste0(readLines("www/tutorial/step5.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step5"),
                    DTOutput(outputId = "step5_table"),
                    tags$h1("Step 6"),
                    tags$p(HTML("In order to finish the remaining parts of the table, we'll need to add some callbacks, which are written in javascript. Callbacks can be used to add more customizations than what is currently possible with just the R helper functions. See code comments below for further explanation. We'll set <code>COLOR_USE</code> to <code>TRUE</code> in order to demonstrate the background color conditional formatting.")),
                    "rowCallback:",
                    tags$pre(paste0(readLines("www/rowCallback.js"), collapse = "\n")),
                    "headerCallback:",
                    tags$pre(paste0(readLines("www/headerCallback.js"), collapse = "\n")),
                    "callback:",
                    tags$pre(paste0(readLines("www/callback.js"), collapse = "\n")),
                    tags$pre(paste0(readLines("www/tutorial/step6.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step6"),
                    DTOutput(outputId = "step6_table"),
                    tags$h1("Step 7"),
                    tags$p(HTML("Finally, we need a way to toggle the background colors on and off. This can be done by changing the value in the <code>COLOR_USE</code> column from TRUE to FALSE and using the <code>replaceData</code> function.")),
                    "include in ui.R",
                    tags$pre(paste0(readLines("www/tutorial/step7_ui.R"), collapse = "\n")),
                    "include in server.R",
                    tags$pre(paste0(readLines("www/tutorial/step7_server.R"), collapse = "\n")),
                    source("www/tutorial/step7_ui.R")[["value"]],
                    DTOutput(outputId = "step7_table"),
                    tags$h1("Step 8"),
                    tags$p("Now that the loss development factor triangle is created, we need to calculate various averages of the factors in each column."),
                    tags$pre(paste0(readLines("www/tutorial/step8.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step8"),
                    tags$h1("Step 9"),
                    tags$p(HTML("Once we have the averages, we can select one set of averages to fill in, i.e. predict, the values for the empty cells in the claim payments triangle. This can be done using the <code>fill_triangle</code> function. We'll use the Two Year averages as the default.")),
                    tags$pre(paste0(readLines("www/tutorial/step9.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step9"),
                    tags$h1("Step 10"),
                    tags$p(HTML("Now we can put the data into a table. Again, we can get pretty close to the final table by just using the options built into the <code>datatable</code> function. The only things still missing at this point is the bold line separating the actual values from the predicted values and to italicize the predicted values. We also still need a way to select which set of averages to use to calculate the predicted values.")),
                    tags$pre(paste0(readLines("www/tutorial/step10.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step10"),
                    DTOutput(outputId = "step10_table"),
                    tags$h1("Step 11"),
                    tags$p("To add the remaining formatting to the table, we'll use a row callback. See code comments below for further explanation."),
                    tags$pre(paste0(readLines("www/rowCallback_filled.js"), collapse = "\n")),
                    tags$pre(paste0(readLines("www/tutorial/step11.R"), collapse = "\n")),
                    verbatimTextOutput(outputId = "step11"),
                    DTOutput(outputId = "step11_table"),
                    tags$h1("Step 12"),
                    tags$p(HTML("Finally, we need a way to change the average selection. This can be done by recalulating the predicted values in the triangle based on the selected set of averages and using the <code>replaceData</code> function.")),
                    "include in ui.R",
                    tags$pre(paste0(readLines("www/tutorial/step12_ui.R"), collapse = "\n")),
                    "include in server.R",
                    tags$pre(paste0(readLines("www/tutorial/step12_server.R"), collapse = "\n")),
                    source("www/tutorial/step12_ui.R")[["value"]],
                    DTOutput(outputId = "step12_table")
           ))