table <- datatable(data = state_a_triangle_dev,
                   escape = FALSE,
                   rownames = FALSE,
                   filter = "none",
                   selection = list(mode = "single", target = "cell"),
                   class = "",
                   colnames = c("Year" = "YEAR",
                                "12:24" = "MONTHS_12_24",
                                "24:36" = "MONTHS_24_36",
                                "36:48" = "MONTHS_36_48",
                                "48:60" = "MONTHS_48_60",
                                "60:72" = "MONTHS_60_72",
                                "72:84" = "MONTHS_72_84",
                                "84:96" = "MONTHS_84_96",
                                "96:108" = "MONTHS_96_108",
                                "108:120" = "MONTHS_108_120"),
                   options = list(paging = FALSE,
                                  searching = FALSE,
                                  ordering = FALSE,
                                  info = FALSE,
                                  columnDefs = list(list(width = "10%", targets = 0),
                                                    list(width = "10%", targets = 1),
                                                    list(width = "10%", targets = 2),
                                                    list(width = "10%", targets = 3),
                                                    list(width = "10%", targets = 4),
                                                    list(width = "10%", targets = 5),
                                                    list(width = "10%", targets = 6),
                                                    list(width = "10%", targets = 7),
                                                    list(width = "10%", targets = 8),
                                                    list(width = "10%", targets = 9),
                                                    list(visible = FALSE, targets = 10:19),
                                                    list(className = "dt-body-right", targets = 1:9),
                                                    list(className = "dt-body-center", targets = 0),
                                                    list(className = "dt-head-center", targets = "_all"))))

table <- table %>%
  formatCurrency(columns = c("12:24", "24:36", "36:48", "48:60", "60:72", "72:84", "84:96", "96:108", "108:120"),
                 currency = "",
                 interval = 3,
                 digits = 3,
                 mark = ",")
