table <- datatable(data = losses_filled,
                   escape = FALSE,
                   rownames = FALSE,
                   filter = "none",
                   selection = "none",
                   class = "",
                   colnames = c("Year" = "YEAR",
                                "12" = "MONTHS_12",
                                "24" = "MONTHS_24",
                                "36" = "MONTHS_36",
                                "48" = "MONTHS_48",
                                "60" = "MONTHS_60",
                                "72" = "MONTHS_72",
                                "84" = "MONTHS_84",
                                "96" = "MONTHS_96",
                                "108" = "MONTHS_108",
                                "120" = "MONTHS_120"),
                   options = list(paging = FALSE,
                                  searching = FALSE,
                                  ordering = FALSE,
                                  info = FALSE,
                                  columnDefs = list(list(width = "10%", targets = 0),
                                                    list(width = "9%", targets = 1),
                                                    list(width = "9%", targets = 2),
                                                    list(width = "9%", targets = 3),
                                                    list(width = "9%", targets = 4),
                                                    list(width = "9%", targets = 5),
                                                    list(width = "9%", targets = 6),
                                                    list(width = "9%", targets = 7),
                                                    list(width = "9%", targets = 8),
                                                    list(width = "9%", targets = 9),
                                                    list(width = "9%", targets = 10),
                                                    list(className = "dt-body-right", targets = 1:10),
                                                    list(className = "dt-body-center", targets = 0),
                                                    list(className = "dt-head-center", targets = "_all"))),
                   caption = tags$caption(style = "caption-side: bottom;",
                                          HTML("<i>Italicized values are estimates.</i>")))

table <- table %>%
  formatCurrency(columns = c("12", "24", "36", "48", "60", "72", "84", "96", "108", "120"),
                 currency = "",
                 interval = 3,
                 digits = 0,
                 mark = ",")
